# Generated by Django 4.0 on 2021-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191120_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.URLField(max_length=250, verbose_name='Длинная ссылка:'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=250, unique=True, verbose_name='Сокращённая ссылка:'),
        ),
    ]
